# Makefile.am: development automation sources

EXTRA_fuse_SOURCES += \
	     automation/artifacts.c \
	     automation/artifacts.h \
	     automation/automation.c \
	     automation/automation.h \
	     automation/json.c \
	     automation/json.h \
	     automation/result_settings.c \
	     automation/result_settings.h \
	     automation/state.c \
	     automation/state.h

if ENABLE_AUTOMATION
fuse_SOURCES += \
	automation/artifacts.c \
	automation/artifacts.h \
	automation/automation.c \
	automation/automation.h \
	automation/json.c \
	automation/json.h \
	automation/result_settings.c \
	automation/result_settings.h \
	automation/state.c \
	automation/state.h
endif
